### ISSUE TITLE
run_status_html is not defined

### ISSUE THREAD

**Issue by hotrovps** [isc-projects/kea-anterius#13]
I got this reponse "run_status_html is not defined" when I access http://server-ip:3000

Server logs:

>  kea-anterius]# npm start
> 
>  kea-anterius@0.0.0 start /root/kea-anterius
>  node ./bin/www
> 
> Anterius Server> Bootup complete
> Anterius Server> OUI Database Loaded
> GET / 500 14.140 ms - 30
> [WS] STATUS: Socket clients (0)
> [WS] STATUS: Socket clients (0)
>

**Comment by Anthrino** [comment]
Thank you for pointing out this issue @hotrovps.
There was a declaration error in the code in [index.js](https://github.com/isc-projects/kea-anterius/blob/master/routes/index.js) file line 187, will fix and commit right away.

**Comment by Anthrino** [comment]
Hi @hotrovps ,
Really sorry for the delay, have fixed the variable declarations causing the error in this [commit](https://github.com/isc-projects/kea-anterius/commit/6c346165776cf31ff358657e853a30fb7b9dd1e1)
Closing this issue, if possible pull and test out the code and reopen in case error persists.
