### ISSUE TITLE
Error when clicking save in adding/editing hostname

### ISSUE THREAD

**Issue by mertzo** [isc-projects/kea-anterius#16]
Hi Team,

I'm trying to deploy kea-anterius on my Debian instance. However, I'm getting an error when trying to add a remote host or even just clicking the save button without any changes.

Please see the attached error and the screenshot.
Thanks in advance!.

Regards,
Mamerto

![image](https://user-images.githubusercontent.com/43633323/46128473-29e31200-c266-11e8-963e-8a183070658a.png)
[2018-09-27T07_02_17_052Z-debug.log](https://github.com/isc-projects/kea-anterius/files/2422830/2018-09-27T07_02_17_052Z-debug.log)

**Comment by Anthrino** [comment]
Thank you for raising this concern. 
This error is part of JSON file processing mentioned in #11 
Working on resolving it.

**Comment by mertzo** [comment]
Thank you! I'll be happy to test it again once this issue is resolved.

Regards,
-Mert

**Comment by Anthrino** [comment]
Hi, 

I have patched the [error](https://github.com/isc-projects/kea-anterius/commit/cceaa804d5c993f0fc3c42996db9a0b52bf09758) that was causing the write problem in JSON settings file.
Closing this issue, please reopen if you experience the same issue after you pull and test the same.
