### ISSUE TITLE
Unable to start kea-anterius

### ISSUE THREAD

**Issue by informatik-bks** [isc-projects/kea-anterius#21]
~/kea-anterius# npm start

> kea-anterius@0.0.0 start /root/kea-anterius
> node ./bin/www

Anterius Server> Bootup complete
Port 3000 is already in use
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kea-anterius@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kea-anterius@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-28T12_09_33_379Z-debug.log

cat /root/.npm/_logs/2018-11-28T12_09_33_379Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kea-anterius@0.0.0~prestart: kea-anterius@0.0.0
6 info lifecycle kea-anterius@0.0.0~start: kea-anterius@0.0.0
7 verbose lifecycle kea-anterius@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kea-anterius@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/kea-anterius/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle kea-anterius@0.0.0~start: CWD: /root/kea-anterius
10 silly lifecycle kea-anterius@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle kea-anterius@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle kea-anterius@0.0.0~start: Failed to exec start script
13 verbose stack Error: kea-anterius@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid kea-anterius@0.0.0
15 verbose cwd /root/kea-anterius
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v9.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error kea-anterius@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the kea-anterius@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Debian Buster with nodeJS 8/9/11 (tried all of them)

If I change the port in bin/www from 3000 to 3001 its starts but with new erros:
npm start

> kea-anterius@0.0.0 start /root/kea-anterius
> node ./bin/www

Anterius Server> Bootup complete
Request Error: connect ECONNREFUSED 192.168.192.123:3001
Request Error: connect ECONNREFUSED 192.168.192.123:3001
Request Error: connect ECONNREFUSED 192.168.192.123:3001
Error 2:  { Error: connect ECONNREFUSED 192.168.192.123:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1121:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.192.123',
  port: 3001 }
Anterius Server> OUI Database Loaded
POST / 404 14.560 ms - 9
Error 2:  Error: Status Code : 404
    at ClientRequest.<anonymous> (/root/kea-anterius/lib/api_service.js:27:35)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:449:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
POST / 404 0.724 ms - 9
Error 2:  Error: Status Code : 404
    at ClientRequest.<anonymous> (/root/kea-anterius/lib/api_service.js:27:35)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:449:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
POST / 404 0.632 ms - 9
......

**Comment by informatik-bks** [comment]
note: but ist still possibel to connect to the gui at port 3001 but after Login I hit another Bug
Cannot read property 'length' of undefined (see https://github.com/isc-projects/kea-anterius/issues/12)

**Comment by Anthrino** [comment]
Hi @informatik-bks 
Thank you for raising this issue, sincere apologies for the delay in response.
Your first error is arising from the nodejs server because port 3000 is being used, hope you've resolved that by switching to another port (3001) or terminating the app occupying 3000.
Could you please pull the latest version from the repo and rerun the application to see if your issue #12 has been resolved, I've tried to patch the source of the bug, not sure if the error has been rectified completely.

**Comment by informatik-bks** [comment]
Hi Anthrino

Will report the test results a soon I have a new test env, just give me a little bit time.
Regards

**Comment by informatik-bks** [comment]
I set up a new test-env with Debian sid, everything looks good with the packges from the distribution (kea). After installing the npm stuff and firing up kea-anterius I still get the same issues. Also when fixing one issue, I get the next.
The code looks for me not ready for production (sorry but this is just my point of view)

regards

**Comment by aumai** [comment]
Is this kea-anterius is now only support Kea 1.4.0 on Ubuntu 16.04.?
I tested on kea 1.5.0 on ubuntu 18.04(https://kb.isc.org/docs/kea-build-on-ubuntu), It doesn't work. It got error.

netadmin@dhcp-kea1:~/kea-anterius$ sudo npm start
[sudo] password for netadmin:

> kea-anterius@0.0.0 start /home/netadmin/kea-anterius
> node ./bin/www

Anterius Server> Bootup complete
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at new WebSocketServer (/home/netadmin/kea-anterius/node_modules/ws/lib/websocket-server.js:68:20)
    at Object.<anonymous> (/home/netadmin/kea-anterius/app.js:358:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kea-anterius@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kea-anterius@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/netadmin/.npm/_logs/2018-12-28T08_08_22_704Z-debug.log

netadmin@dhcp-kea1:~/kea-anterius$ more /home/netadmin/.npm/_logs/2018-12-28T08_08_22_704Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kea-anterius@0.0.0~prestart: kea-anterius@0.0.0
6 info lifecycle kea-anterius@0.0.0~start: kea-anterius@0.0.0
7 verbose lifecycle kea-anterius@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kea-anterius@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/netadmin/kea-anterius/node_module
s/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle kea-anterius@0.0.0~start: CWD: /home/netadmin/kea-anterius
10 silly lifecycle kea-anterius@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle kea-anterius@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle kea-anterius@0.0.0~start: Failed to exec start script
13 verbose stack Error: kea-anterius@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid kea-anterius@0.0.0
15 verbose cwd /home/netadmin/kea-anterius
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error kea-anterius@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the kea-anterius@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



I found this in https://github.com/isc-projects/kea-anterius/releases that

Anterius tested only with Kea 1.4.0 on Ubuntu 16.04.
Source project code clean up and refactoring in progress.
Stability issues with certain frontend features attributed to dynamic html rendering at NodeJS backend.
Log streaming and Server Boot ops not extended for remote servers.
CPU Utilizn, server status info unavailable with CA api data.

**Comment by tuyenld** [comment]
Hi @Anthrino 

I got same issue with @aumai. Did you fix it?

**Comment by informatik-bks** [comment]
Dear tuyenld sorry for my late reply, I was a little busy with other projects. I will have a look at it and post a reply in a few days when I have time

**Comment by informatik-bks** [comment]
ups totaly forgot to do somthing... but finally I tested it and it works!
It works but I need to compile KEA from Source, it does not work with the Debian Packages!
Test-Machine: Debian 10, KEA 1.7.4, NodeJS Version 12
Please close the Ticket

**Comment by satishdotpatel** [comment]
I am getting same error on CentOS 7.5 and i have installed kea with RPM packages
