### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by vrisk** [isc-projects/kea-anterius#7]
Jerin - you need to tag an initial version.

I would suggest maybe, use version 0.5, something like that. (I created a milestone for that, but you can change the number - I would just suggest <1.0 to indicate it is still sort of experimental).

Then, create some release notes, listing the main features supported, listing the main outstanding issues, acknowledging the Glass project and GSOC.

**Comment by Anthrino** [comment]
@vrisk I had added a release draft to the repo, hadn't published it before verifying code stability.
