### ISSUE TITLE
Radius support?

### ISSUE THREAD

**Issue by denji** [isc-projects/kea-anterius#9]

**Comment by tomaszmrugalski** [comment]
Kea supports RADIUS via premium hook. This is not supported in Anterius yet.

Can yo write a bit more what would you like to do with Radius?

Right now Anterius is finishing its initial development phase as GSoC project. However, ISC is interested in evaluating how popular it would be if we decided to adopt it and continue its development.

Would you be willing to fund development of the Radius support for it? Would you be interested in participating in tests of early engineering versions?

**Comment by denji** [comment]
> Can yo write a bit more what would you like to do with Radius?

We have FreeRADIUS without DHCP, we would like to test the operation of Radius before a possible purchase.

> Would you be interested in participating in tests of early engineering versions?

Yes, for isolated testing in test environment.

I will close the topic, since the final stage of development of the GSoC project.
